export const envConfig = {
  CLERK_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,
  CLERK_SECRET_KEY: process.env.NEXT_PUBLIC_CLERK_SECRET_KEY,

  // MONGODB URI
  MONGODB_URI: process.env.MONGODB_URI,

  // ADMIN CREDENTIALS
  CLERK_ADMIN_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_CLERK_ADMIN_PUBLISHABLE_KEY,
  CLERK_ADMIN_SECRET_KEY: process.env.CLERK_ADMIN_SECRET_KEY,
}